name: Android CI x86_64

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Swift toolchain 5.4.2
      run: wget https://swift.org/builds/swift-5.4.2-release/xcode/swift-5.4.2-RELEASE/swift-5.4.2-RELEASE-osx.pkg;
        sudo installer -pkg swift-5.4.2-RELEASE-osx.pkg -target /
    - name: Install NDK
      run: wget https://dl.google.com/android/repository/android-ndk-r21e-darwin-x86_64.zip;
        unzip android-ndk-r21e-darwin-x86_64.zip
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android-5.4-r1.zip;
        unzip swift-android-5.4-r1.zip;
        rm -rf swift-android-5.4-r1.zip;
        swift-android-5.4-r1/bin/swift-android tools --update;
        ln -sfn swift-android-5.4-r1 swift-android-current
    - name: Download Android Emulator
      run: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-29;google_apis;x86_64"
    - name: Create Android Emulator
      run: $ANDROID_HOME/tools/bin/avdmanager create avd -n ci-test -k "system-images;android-29;google_apis;x86_64" -d "pixel" --force
    - name: Start Android Emulator
      run: $ANDROID_HOME/emulator/emulator -no-window -avd ci-test -noaudio > /dev/null &
    - name: Run connected android tests
      run: export TOOLCHAINS=org.swift.540202104261a;
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android-current;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        adb wait-for-device;
        ./gradlew sample:cAT
