name: CI Test

on: [pull_request]

jobs:

  android-x86_64:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v1
    - name: Select XCode 14.2
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app
    - name: Install NDK
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android.zip;
        unzip swift-android.zip;
        swift-android/bin/swift-android tools --update;
    - name: Install Android Emulator
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-29;google_apis;x86_64"
    - name: Create Android Emulator
      run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n ci-test -k "system-images;android-29;google_apis;x86_64" -d "pixel" --force
    - name: Start Android Emulator
      run: $ANDROID_HOME/emulator/emulator -no-window -avd ci-test -noaudio > /dev/null &
    - name: Run connected android tests
      run: export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        adb wait-for-device;
        ./gradlew sample:cAT

  android-arm64-v8a:
    runs-on: macos-13-xlarge
    
    steps:
    - uses: actions/checkout@v1
    - name: Select XCode 14.2
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app
    - name: Install NDK
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android.zip;
        unzip swift-android.zip;
        swift-android/bin/swift-android tools --update;
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Install Android Emulator
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-29;google_apis;arm64-v8a"
    - name: Create Android Emulator
      run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n ci-test -k "system-images;android-29;google_apis;arm64-v8a" -d "pixel" --force
    - name: Start Android Emulator
      run: $ANDROID_HOME/emulator/emulator -no-window -avd ci-test -noaudio > /dev/null &
    - name: Run connected android tests
      run: export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        adb wait-for-device;
        ./gradlew sample:cAT
